package com.innvo.process
import com.innvo.domain.Route;
import com.innvo.domain.Score;
import org.json.JSONObject;
import com.innvo.drools.SaveScoreExecutor;
import com.innvo.web.rest.util.RouteUtil;
import com.innvo.domain.enumeration.Status;
global org.kie.api.runtime.KieSession kSession;
import java.util.HashMap;
import java.util.Map;
import com.innvo.SaveScoreHandler;
 
rule "Two"
ruleflow-group "Group2"

dialect "java"
    
    when
        
        p : Route()
        hostname:String()
        eval(hostname!=null && p.getId()==5202)
    
    then       	
       	
       	Score score = new Score();
        JSONObject details = new JSONObject();
		details.put("ScenarioName", "Scenario_One");
		details.put("ScoreCategoryName", "Category_One 1");
		details.put("Value", 52);
		details.put("RuleName", "innvorulefile");
        score.setRunid(24l);
        score.setDomain("My Domain");
		score.setStatus(Status.Active);
		score.setValue(52.0);
		score.setRulename("My Rule");
		score.setLastmodifiedby("Demo");
        System.out.println(score);        
        SaveScoreHandler scoreVal = new SaveScoreHandler(score);
end

