package com.innvo.process
import com.innvo.domain.Route;
import com.innvo.domain.Score;
import org.json.JSONObject;
import com.innvo.drools.SaveScoreExecutor;
import com.innvo.web.rest.util.RouteUtil;
import com.innvo.domain.enumeration.Status;
 
rule "One"
ruleflow-group "Group1"

dialect "java"
    
    when
        
        p : RouteUtil()
        hostname:String()
        eval(hostname!=null && p.getRouteId()==5202)
    
    then
       	Score score = new Score();
        JSONObject details = new JSONObject();
		details.put("ScenarioName", "Scenario_One");
		details.put("ScoreCategoryName", "Category_One 1");
		details.put("Value", 52);
		details.put("RuleName", "innvorulefile");
        score.setRunid(24l);
        score.setDomain("My Domain");
		score.setStatus(Status.Active);
		score.setValue(52.0);
		score.setRulename("My Rule");
		score.setLastmodifiedby("Demo");
        System.out.println(score);
   		SaveScoreExecutor saveScoreExecutor=new SaveScoreExecutor();
        saveScoreExecutor.saveScore(score,hostname);
       
end


