package com.drools.poc
 
import com.innvo.drools.Todo
import com.innvo.domain.Score
import com.innvo.domain.enumeration.Status
import org.json.JSONObject
 
rule "Rule_one_routeRuleTwo"
dialect "mvel" 
    when
        Todo : Todo( value: value,runId:runId,status :status, domain:domain,lastmodifiedby:lastmodifiedby,lastmodifieddate:lastmodifieddate
        ,objrecordtype:objrecordtype,objclassification:objclassification,objcategory:objcategory,route:route,ruleName:ruleName)
    then
        Score $score = new Score();
        JSONObject details = new JSONObject();
		details.put("ScenarioName", "Scenario_One");
		details.put("ScoreCategoryName", "Category_One 1");
		details.put("Value", value);
		details.put("RuleName", ruleName);
        $score.setRunid(runId);
        $score.setDomain(domain);
		$score.setStatus(status);
		$score.setValue(value);
		$score.setDetails(details);
		$score.setRulename(ruleName);
		$score.setLastmodifiedby(lastmodifiedby);
		$score.setLastmodifieddate(lastmodifieddate)
        $score.setObjrecordtype(objrecordtype);
        $score.setObjclassification(objclassification);
        $score.setObjcategory(objcategory);
        $score.setRoute(route)
        insert($score);
end

rule "Rule_one_routeRuleTwo"
dialect "mvel" 
    when
        Todo : Todo( value: value,runId:runId,status :status, domain:domain,lastmodifiedby:lastmodifiedby,lastmodifieddate:lastmodifieddate
        ,objrecordtype:objrecordtype,objclassification:objclassification,objcategory:objcategory,route:route,ruleName:ruleName)
    then
        Score $score = new Score();
        JSONObject details = new JSONObject();
		details.put("ScenarioName", "Scenario_Two");
		details.put("ScoreCategoryName", "Category_Two 2");
		details.put("Value", value);
		details.put("RuleName", ruleName);
        $score.setRunid(runId);
        $score.setDomain(domain);
		$score.setStatus(status);
		$score.setValue(value);
		$score.setDetails(details);
		$score.setRulename(ruleName);
		$score.setLastmodifiedby(lastmodifiedby);
		$score.setLastmodifieddate(lastmodifieddate)
        $score.setObjrecordtype(objrecordtype);
        $score.setObjclassification(objclassification);
        $score.setObjcategory(objcategory);
        $score.setRoute(route)
        insert($score);
end
