package com.drools.poc
 
import com.innvo.drools.ScoreRouteRulefile;
import com.innvo.domain.Score
import com.innvo.domain.enumeration.Status
import org.json.JSONObject
import java.util.List
import com.innvo.domain.Route
import com.innvo.domain.Scorefactor
 
rule "Rule_one"
agenda-group "group one"
salience 100
dialect "mvel" 

    when
    
       $scoreRouteRulefile : ScoreRouteRulefile($scorefactors : scorefactors)
       $value :Scorefactor() from $scorefactors

       $scoreRouteRulefile1 : ScoreRouteRulefile($value.getMatchvalue()==location.getZippostcode(), route:route,value: value,runId:runId,status :status, domain:domain,lastmodifiedby:lastmodifiedby,lastmodifieddate:lastmodifieddate
        ,objrecordtype:objrecordtype,objclassification:objclassification,objcategory:objcategory,ruleName:ruleName)    
    then

        Score $score = new Score();
        JSONObject details = new JSONObject();
		details.put("ScenarioName", "Scenario_One");
		details.put("ScoreCategoryName", "Category_One 1");
		details.put("Value", $value.getMatchvalue());
		details.put("RuleName", "Rule_one");
        $score.setDetails(details.toString());
        $score.setRunid(runId);
        $score.setDomain(domain);
		$score.setStatus(status);
		$score.setValue(Double.parseDouble($value.getMatchvalue()));
		$score.setRulename("Rule_one");
		$score.setLastmodifiedby(lastmodifiedby);
		$score.setLastmodifieddate(lastmodifieddate)
        $score.setObjrecordtype(objrecordtype);
        $score.setObjclassification(objclassification);
        $score.setObjcategory(objcategory);
        $score.setRoute(route)
        System.out.println($score);
        insert($score);
        kcontext.getKnowledgeRuntime().getAgenda().getAgendaGroup("group two").setFocus();
end

rule "Rule_two"
agenda-group "group two"
salience 200
dialect "mvel" 
    when
        $scoreRouteRulefile : ScoreRouteRulefile();
    then
       System.out.println("---------------------------------------");

end