package com.drools.poc
 
import com.innvo.drools.Todo
import com.innvo.domain.Score
import com.innvo.domain.enumeration.Status
import org.json.JSONObject
 
rule "Rule_one"
dialect "mvel" 
    when
        Todo : Todo( runId:runId, status :status, domain:domain, lastmodifiedby:lastmodifiedby, lastmodifieddate:lastmodifieddate,
        route:route, ruleName:ruleName)
    then
        Score $score = new Score();
        JSONObject details = new JSONObject();
		details.put("ScenarioName", "Scenario_One");
		details.put("ScoreCategoryName", "Category_One 1");
		details.put("Value", 1000);
		details.put("RuleName", ruleName);
        $score.setRunid(runId);
        $score.setDomain(domain);
	$score.setStatus(status);
		
	$score.setDetails(details);
	$score.setRulename(ruleName);
	$score.setLastmodifiedby(lastmodifiedby);
	$score.setLastmodifieddate(lastmodifieddate)
      
        $score.setRoute(route)
        insert($score);
end

