package com.drools.poc
 
import com.innvo.drools.Todo
import com.innvo.domain.Score
import com.innvo.domain.enumeration.Status
 
rule "Odd Rule"
dialect "mvel" 
    when
        Todo : Todo( value: value,runId:runId,status :status, domain:domain,details:details,lastmodifiedby:lastmodifiedby,lastmodifieddate:lastmodifieddate
        ,objrecordtype:objrecordtype,objclassification:objclassification,objcategory:objcategory,route:route)
    then
        Score $score = new Score();
        $score.setRunid(runId);
        $score.setDomain(domain);
		$score.setStatus(status);
		$score.setValue(value);
		$score.setDetails(details);
		$score.setRulename("r_count_segments");
		$score.setLastmodifiedby(lastmodifiedby);
		$score.setLastmodifieddate(lastmodifieddate)
        $score.setObjrecordtype(objrecordtype);
        $score.setObjclassification(objclassification);
        $score.setObjcategory(objcategory);
        $score.setRoute(route)
        insert($score);
end