package com.drools.poc
 
import com.innvo.drools.Todo
import com.innvo.domain.Score
import com.innvo.domain.enumeration.Status
import org.json.JSONObject
 
rule "Rule_one"
agenda-group "group one"
salience 100
dialect "mvel" 

    when
        $todo : Todo(route.getId() > 5200 ,route:route,value: value,runId:runId,status :status, domain:domain,lastmodifiedby:lastmodifiedby,lastmodifieddate:lastmodifieddate
        ,objrecordtype:objrecordtype,objclassification:objclassification,objcategory:objcategory,ruleName:ruleName)
    then
        Score $score = new Score();
        JSONObject details = new JSONObject();
		details.put("ScenarioName", "Scenario_One");
		details.put("ScoreCategoryName", "Category_One 1");
		details.put("Value", 52);
		details.put("RuleName", ruleName);
        $score.setRunid(runId);
        $score.setDomain(domain);
		$score.setStatus(status);
		$score.setValue(52);
		$score.setDetails(details);
		$score.setRulename(ruleName);
		$score.setLastmodifiedby(lastmodifiedby);
		$score.setLastmodifieddate(lastmodifieddate)
        $score.setObjrecordtype(objrecordtype);
        $score.setObjclassification(objclassification);
        $score.setObjcategory(objcategory);
        $score.setRoute(route)
        System.out.println($score);
        insert($score);
        kcontext.getKnowledgeRuntime().getAgenda().getAgendaGroup("group two").setFocus();
end

rule "Rule_two"
agenda-group "group two"
salience 200
dialect "mvel" 
    when
        Todo : Todo();
    then
        drools.halt()
end